@startuml braille
' skinparam linetype polyline

together {
    class board {
        cell : int
        buttons : int
    }

        cell --|> board
        cell : pin (object)
        button --|> board
        pin --|> cell

    class pin {
        info : int
        asciiChar : string
        void togglePin()
        void asciiCharConvert()
    }

        pin <|-- BrailleTables : info from
        BrailleTables : char [][6] letterList
        BrailleTables : char [][6] numberList
        BrailleTables : string [] wordList

    class button {
        debounce : float 
        void next() 
        void previous()
        void mode()
    }

        button --> pin : passes info
        button --> mode : changes val

}

together {

    class GPIOExtender {
        
    }

        GPIOExtender <-- pin

    class ESP32 {

    } 

        ESP32 <|-- GPIOExtender

    class I2C {

    }

        ESP32 <|-- I2C

    class RS485 {

    }

        I2C <|-- RS485 

}

class SD {
    void playAudio()
}

    SD <|-- audioList 
    audioList : string [] audioTrack
    mode --> SD : tells SD to play
    GPIOExtender --> SD : tells SD to play

class led {
    void light()
}

    led <-- mode : mode lights color

enum mode {
    Letter
    Number
    Word
} 

@enduml