@startuml braille

class pin {
    info : int [6]
    asciiChar : string
    void togglePin()
    void asciiCharConvert()
}

    pin::info <-- Tables : info goes to
    Tables : char [][6] letterList
    Tables : char [][6] numberList
    Tables : string [] letterList

class button {
    debounce : float 
    void next() 
    void previous()
    void mode()
}

class sd {
    void playAudio()
}

    sd <|-- audioList 
    audioList : string [] audioTrack

class led {
    void light()
}

    led::light --> mode : uses

enum mode {
    Letter
    Number
    Word
} 

    button::next ---> pin::togglePin : calls, changes info & ascii val in pin
    button::previous ---> pin::togglePin : calls, changes info & ascii val in pin
    button::mode --> mode : has, mode() changes enum val

@enduml