@startuml ESP32

together {

    class ESP32 {
        void setup()
    }

    class I2CController {
        Don't change the clock speed!
        void setup()
    }

    class RS485 {
        void setup()
    }

    class GPIOExtender {
        void setup()
    }

    GPIOExtender --|> ESP32
    I2CController --> ESP32 : connected 
    RS485 --|> I2CController

}

@enduml