@startuml ESP32

together {

    class ESP32 {
        - I2C I2CInterface
        - I2S I2SInterface
        void init()
    }

    class I2CInterface {
        - GPIOExpander MCP23017
        void init()
    }

    class I2SInterface {
        void init()
    }

    class ATTINY {
        - RS485 RS485
        #Don't change the clock speed!
        void init()
        
    }

    class RS485 {
        #Define receiver/driver pin
        void init()
    }

    class MCP23017 {
        #define GPIO inputs
        #define GPIO outputs
        #setup busses
        void init()
    }

    ESP32 --|> I2CInterface
    ESP32 --|> I2SInterface
    MCP23017 --> I2CInterface
    ATTINY --> MCP23017 : connected 
    RS485 <|-- ATTINY

}

@enduml